[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 34, in select_next_node
    sorted_nodes = sorted(unvisited_nodes, key=lambda x: probabilities[unvisited_nodes.index(x)], reverse=True)
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 34, in <lambda>
    sorted_nodes = sorted(unvisited_nodes, key=lambda x: probabilities[unvisited_nodes.index(x)], reverse=True)
AttributeError: 'set' object has no attribute 'index'
