[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py:19: RuntimeWarning: divide by zero encountered in scalar divide
  sub_path_score = 0.3 * (distance_to_node + distance_to_dest) / distance_matrix[current_node][destination_node]
D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py:26: RuntimeWarning: invalid value encountered in scalar divide
  normalized_scores = [s / sum(scores) for s in scores]
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 27, in select_next_node
    next_node = node_list[np.random.choice(len(node_list), p=normalized_scores)]
NameError: name 'np' is not defined
