[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 4, in select_next_node
    perturbed_distances = {
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 5, in <dictcomp>
    node: distance_matrix[current_node][node] + exploration_factor * np.random.rand()
NameError: name 'np' is not defined
