[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "numpy\\random\\mtrand.pyx", line 941, in numpy.random.mtrand.RandomState.choice
TypeError: 'set' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 10, in select_next_node
    next_node = np.random.choice(unvisited_nodes, p=probabilities)
  File "numpy\\random\\mtrand.pyx", line 943, in numpy.random.mtrand.RandomState.choice
ValueError: a must be 1-dimensional or an integer
