[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 11, in select_next_node
    future_potential = harmonic_mean(future_distances) if future_distances else 0
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 28, in harmonic_mean
    return next_node
NameError: name 'next_node' is not defined
