[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py:20: RuntimeWarning: divide by zero encountered in scalar divide
  dynamic_weight = 0.3 * (1 - (distance_to_dest / sum(distance_matrix[node][n] for n in unvisited_nodes if n != node)))
D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py:39: RuntimeWarning: invalid value encountered in scalar multiply
  dynamic_weight * normalized_centroid_penalty +
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 52, in eval_heuristic
    raise KeyError(f"Node {next_node} is already visited.")
KeyError: 'Node None is already visited.'
