Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 11, in <module>
    from gpt import select_next_node_v2 as select_next_node
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 38
    global path_memory
    ^^^^^^^^^^^^^^^^^^
SyntaxError: name 'path_memory' is used prior to global declaration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 13, in <module>
    from gpt import select_next_node
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 38
    global path_memory
    ^^^^^^^^^^^^^^^^^^
SyntaxError: name 'path_memory' is used prior to global declaration
